/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.managerment_library.views;

import com.managerment_library.controller.BooksController;
import com.managerment_library.controller.CatgoryController;
import com.managerment_library.controller.UserController;
import com.managerment_library.entity.BooksEntity;
import com.managerment_library.entity.CatgoryEntity;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    Vector table_tieuDe = new Vector();
    Vector table_duLieu = new Vector();

    private final UserController userController = new UserController();
    private final BooksController booksController = new BooksController();
    private final CatgoryController catgoryController = new CatgoryController();

    public User() {
        initComponents();
        table_tieuDe.clear();
        table_tieuDe.add("STT");
        table_tieuDe.add("Tên sách");
        table_tieuDe.add("Tên tác giả");
        table_tieuDe.add("Thể loại");
        table_tieuDe.add("Tình trạng sách");
        table_duLieu.clear();
        List<BooksEntity> books = booksController.getAll();
        CatgoryEntity catgoryEntity = null;
        for (int i = 0; i < books.size(); i++) {
            Vector temp = new Vector();
            temp.add(i + 1);
            temp.add(books.get(i).getName());
            temp.add(books.get(i).getAuthor());
            String catgoryBook = books.get(i).getCatgoryEntity().stream()
                    .map(item -> item.getCatgory()).collect(Collectors.joining(","));
            temp.add(catgoryBook);
            if (books.get(i).getAmount() == 0) {
                temp.add("Hết sách");
            } else {
                temp.add("còn sách");
            }
            table_duLieu.add(temp);
        }
        DefaultTableModel model = new DefaultTableModel(table_duLieu, table_tieuDe) {
            @Override
            public boolean isCellEditable(int i, int i1) {
//                    if ((i1 == 0) || (i1 == 2)) {
//                        return true;
//                    } else {
//                        return false;
//                    }
                return false;
            }
        };
        jTable1.setModel(model);
        Map<Long, String> mapCatgory = catgoryController.getMapCatgory();
        user_JComboBox_catgory.removeAllItems();
        user_JComboBox_catgory.addItem("");
        mapCatgory.forEach((k,v) -> {
            user_JComboBox_catgory.addItem(v);
        });
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_loginForm = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loginForm_JuserNameField = new javax.swing.JTextField();
        loginForm_JpasswordField = new javax.swing.JPasswordField();
        loginForm_btn_login = new javax.swing.JButton();
        jDialog_loginForm_message = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user_JtextFieldSearchNameBook = new javax.swing.JTextField();
        user_JtextFieldSearchNameAuthor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_btn_Search = new javax.swing.JButton();
        user_JComboBox_catgory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        user_btn_Login = new javax.swing.JButton();

        jLabel4.setText("Tên đăng nhập");

        jLabel6.setText("Mật khẩu");

        loginForm_JpasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginForm_JpasswordFieldActionPerformed(evt);
            }
        });

        loginForm_btn_login.setText("Đăng nhập");
        loginForm_btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginForm_btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_loginFormLayout = new javax.swing.GroupLayout(jDialog_loginForm.getContentPane());
        jDialog_loginForm.getContentPane().setLayout(jDialog_loginFormLayout);
        jDialog_loginFormLayout.setHorizontalGroup(
            jDialog_loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_loginFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginForm_btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jDialog_loginFormLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jDialog_loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDialog_loginForm_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialog_loginFormLayout.createSequentialGroup()
                        .addGroup(jDialog_loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog_loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginForm_JpasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginForm_JuserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );
        jDialog_loginFormLayout.setVerticalGroup(
            jDialog_loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_loginFormLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jDialog_loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loginForm_JuserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDialog_loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(loginForm_JpasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(loginForm_btn_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDialog_loginForm_message, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tìm Kiếm theo tên tác giả");

        user_JtextFieldSearchNameBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_JtextFieldSearchNameBookActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm kiếm theo tên sách");

        jLabel3.setText("Tìm kiếm theo thể loại");

        user_btn_Search.setText("Tìm kiếm");
        user_btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_btn_SearchActionPerformed(evt);
            }
        });

        user_JComboBox_catgory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user_JtextFieldSearchNameAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_JtextFieldSearchNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(user_JComboBox_catgory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(user_btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(user_JtextFieldSearchNameAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(user_JtextFieldSearchNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(user_btn_Search))
                    .addComponent(user_JComboBox_catgory))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        user_btn_Login.setText("Đăng nhập");
        user_btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_btn_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(user_btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_btn_Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_JtextFieldSearchNameBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_JtextFieldSearchNameBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_JtextFieldSearchNameBookActionPerformed

    private void loginForm_JpasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginForm_JpasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginForm_JpasswordFieldActionPerformed

    private void user_btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_btn_LoginActionPerformed
        jDialog_loginForm.setSize(450, 350);
        jDialog_loginForm.setVisible(true);
        jDialog_loginForm.setLocationRelativeTo(this);
    }//GEN-LAST:event_user_btn_LoginActionPerformed

    private void loginForm_btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginForm_btn_loginActionPerformed
        String userName = loginForm_JuserNameField.getText();
        String password;
        password = String.valueOf(loginForm_JpasswordField.getPassword());
        String role = isExistUser(userName, password);
        if (role != null) {
            Manager manager = new Manager(role);
            manager.setVisible(true);
            manager.setLocationRelativeTo(null);
            jDialog_loginForm.dispose();
            this.dispose();
        }
    }//GEN-LAST:event_loginForm_btn_loginActionPerformed

    private void user_btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_btn_SearchActionPerformed
        String name = user_JtextFieldSearchNameBook.getText();
        String catgory = user_JComboBox_catgory.getSelectedItem().toString();
        String author = user_JtextFieldSearchNameAuthor.getText();
        List<BooksEntity> resultSearch = booksController.resultSearch(name, author, catgory);
        table_tieuDe.clear();
        table_tieuDe.add("STT");
        table_tieuDe.add("Tên sách");
        table_tieuDe.add("Tên tác giả");
        table_tieuDe.add("Thể loại");
        table_tieuDe.add("Tình trạng sách");
        table_duLieu.clear();
        for (int i = 0; i < resultSearch.size(); i++) {
            Vector temp = new Vector();
            temp.add(i + 1);
            temp.add(resultSearch.get(i).getName());
            temp.add(resultSearch.get(i).getAuthor());
            String catgoryBook = resultSearch.get(i).getCatgoryEntity().stream()
                    .map(item -> item.getCatgory()).collect(Collectors.joining(","));
            temp.add(catgoryBook);
            if (resultSearch.get(i).getAmount() == 0) {
                temp.add("Hết sách");
            } else {
                temp.add("còn sách");
            }
            table_duLieu.add(temp);
        }
        DefaultTableModel model = new DefaultTableModel(table_duLieu, table_tieuDe) {
            @Override
            public boolean isCellEditable(int i, int i1) {
//                    if ((i1 == 0) || (i1 == 2)) {
//                        return true;
//                    } else {
//                        return false;
//                    }
                return false;
            }
        };
        jTable1.setModel(model);
    }//GEN-LAST:event_user_btn_SearchActionPerformed

    private String isExistUser(String userName, String password) {
        return userController.isExistUser(userName, password);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog_loginForm;
    private javax.swing.JLabel jDialog_loginForm_message;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField loginForm_JpasswordField;
    private javax.swing.JTextField loginForm_JuserNameField;
    private javax.swing.JButton loginForm_btn_login;
    private javax.swing.JComboBox<String> user_JComboBox_catgory;
    private javax.swing.JTextField user_JtextFieldSearchNameAuthor;
    private javax.swing.JTextField user_JtextFieldSearchNameBook;
    private javax.swing.JButton user_btn_Login;
    private javax.swing.JButton user_btn_Search;
    // End of variables declaration//GEN-END:variables
}
